### ISSUE TITLE
这个项目和社区另一个项目monitor-prometheus都能导出kitex的一些metric？应该如何选择？

### ISSUE THREAD

**Issue by zzzzer91** [kitex-contrib/obs-opentelemetry#21]
另一个项目：https://github.com/kitex-contrib/monitor-prometheus

**Comment by joway** [comment]
<img width="826" alt="image" src="https://github.com/kitex-contrib/obs-opentelemetry/assets/8353464/39c3782c-d0e6-495a-acce-0e62b01f27b2">
<img width="810" alt="image" src="https://github.com/kitex-contrib/obs-opentelemetry/assets/8353464/0a54f3ae-dfc6-4cd2-8ac4-cb6ba530454f">

**Comment by zzzzer91** [comment]
@joway  其实我的意思是指这个项目也导出了一些kitex的prometheus metric，感觉和另一个项目重复了😂


![image](https://github.com/kitex-contrib/obs-opentelemetry/assets/24646819/2a6d4569-2eca-47a8-8464-97ef4f0406c5)

**Comment by rogerogers** [comment]
不重复，两种不同的实现，opentlemetry metrics使用起来更灵活，prometheus更贴合prometheus生态，使用也比较简单方便
