### ISSUE TITLE
import  github.com/kitex-contrib/obs-opentelemetry/provider error

### ISSUE THREAD

**Issue by huerni** [kitex-contrib/obs-opentelemetry#23]
question：
github.com/kitex-contrib/obs-opentelemetry/provider imports
        go.opentelemetry.io/otel/metric/global: module go.opentelemetry.io/otel/metric@latest found (v1.16.0), but does not contain package go.opentelemetry.io/otel/metric/global

Why does this problem occur, please?

**Comment by rogerogers** [comment]
The new version needs to be released, please wait a moment.

**Comment by CoderPoet** [comment]
> question： github.com/kitex-contrib/obs-opentelemetry/provider imports go.opentelemetry.io/otel/metric/global: module go.opentelemetry.io/otel/metric@latest found (v1.16.0), but does not contain package go.opentelemetry.io/otel/metric/global
> 
> Why does this problem occur, please?

The new version has been released, please try again: https://github.com/kitex-contrib/obs-opentelemetry/releases/tag/v0.2.3
