### ISSUE TITLE
我想在使用zap的实例，hlog.CtxDebugf(ctx,"test")默认打印ctx里的logid，我可以在hlog哪里注入呢

### ISSUE THREAD

**Issue by tankpanv** [kitex-contrib/obs-opentelemetry#24]
我想在使用zap的实例，hlog.CtxDebugf(ctx,"test")默认打印ctx里的logid，我可以在hlog哪里注入呢

**Comment by rogerogers** [comment]
zap目前不支持打印ctx里的其他信息，晚点我可以加一下
有什么好的想法和建议，可以issue说明，也欢迎pr

**Comment by li-jin-gou** [comment]
already fix
