### ISSUE TITLE
我想在上游go服务通过kitex client请求kitex服务的把trace_id 的信息传到下游服务，我应该通过哪个函数可以设置传下去的trace信息呢

### ISSUE THREAD

**Issue by tankpanv** [kitex-contrib/obs-opentelemetry#25]
我想在上游go服务通过kitex client请求kitex服务的把trace_id 的信息传到下游服务，我应该通过哪个函数可以设置传下去的trace信息呢，有demo可以参考一下吗，我在仓库里没有找到这块的使用

**Comment by CoderPoet** [comment]
> 我想在上游go服务通过kitex client请求kitex服务的把trace_id 的信息传到下游服务，我应该通过哪个函数可以设置传下去的trace信息呢，有demo可以参考一下吗，我在仓库里没有找到这块的使用

简单来说，你只需要在你的 client 里加上一个 suite 就行

```
client.WithSuite(tracing.NewClientSuite())
```

具体完整 demo 在这里哈：https://github.com/CoderPoet/kitex-examples/tree/main/opentelemetry

**Comment by tankpanv** [comment]
> > 我想在上游go服务通过kitex client请求kitex服务的把trace_id 的信息传到下游服务，我应该通过哪个函数可以设置传下去的trace信息呢，有demo可以参考一下吗，我在仓库里没有找到这块的使用
> 
> 简单来说，你只需要先初始化下 otel provider，然后在你的 client 里加上一个 suite 就行
> 
> ```
> client.WithSuite(tracing.NewClientSuite())
> ```
> 
> 具体完整 demo 在这里哈：https://github.com/cloudwego/kitex-examples/blob/main/opentelemetry/client/main.go#L56

我不是很理解这个例子，我想做的事情是，读取上游的request_id ，然后把在调用kitex client 的时候把这个request_id 作为trace_id 传下去，，这个怎么可以做到呢。比如我应该把这个request_id 写入到ctx里的哪个结构体里呢

**Comment by CoderPoet** [comment]
> > > 我想在上游go服务通过kitex client请求kitex服务的把trace_id 的信息传到下游服务，我应该通过哪个函数可以设置传下去的trace信息呢，有demo可以参考一下吗，我在仓库里没有找到这块的使用
> > 
> > 
> > 简单来说，你只需要先初始化下 otel provider，然后在你的 client 里加上一个 suite 就行
> > ```
> > client.WithSuite(tracing.NewClientSuite())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 具体完整 demo 在这里哈：https://github.com/cloudwego/kitex-examples/blob/main/opentelemetry/client/main.go#L56
> 
> 我不是很理解这个例子，我想做的事情是，读取上游的request_id ，然后把在调用kitex client 的时候把这个request_id 作为trace_id 传下去，，这个怎么可以做到呢。比如我应该把这个request_id 写入到ctx里的哪个结构体里呢

噢噢 抱歉，理解错你意思了。你如果是想自定义 traceid 取值逻辑，可以考虑自定义一个 propagator ，注入到 otel provider 里来实现哈

参考：https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/ot/ot_propagator.go#L162
