### ISSUE TITLE
span状态设置问题

### ISSUE THREAD

**Issue by tianming244052** [kitex-contrib/obs-opentelemetry#27]
https://github.com/kitex-contrib/obs-opentelemetry/blob/c76e27f58391e7be84d8c71786151c72676aed8e/logging/zap/logger.go#L160

 为什么不使用  >= 判断。  这样我打印info日志 span的状态就为ok,  error日志span的状态就可以是error

**Comment by rogerogers** [comment]
看了下，是个bug，方便pr修复下吗

**Comment by rogerogers** [comment]
fixed by #30
