### ISSUE TITLE
recordStackTraceInSpan param do not use 

### ISSUE THREAD

**Issue by zstone12** [kitex-contrib/obs-opentelemetry#4]
logging/logrus/option.go
`func WithRecordStackTraceInSpan(recordStackTraceInSpan bool) Option {
	return option(func(cfg *config) {
		cfg.traceHookConfig.recordStackTraceInSpan = true
	})
}
`

**Comment by zstone12** [comment]
I think can remove the param or `cfg.traceHookConfig.recordStackTraceInSpan = recordStackTraceInSpan `

**Comment by CoderPoet** [comment]
> I think remove the param or use it `cfg.traceHookConfig.recordStackTraceInSpan = recordStackTraceInSpan `

Thanks for the reminder, there is indeed a problem, thanks for your PR
