### ISSUE TITLE
Will  this support OLTP Trace over HTTP?

### ISSUE THREAD

**Issue by systemview2018** [kitex-contrib/obs-opentelemetry#42]

**Comment by rogerogers** [comment]
可以通过 `WithSdkTracerProvider` 配置成需要的 exporter

**Comment by rogerogers** [comment]
https://github.com/cloudwego/biz-demo/blob/b0b848231865af4c43f2ed0b8d5967eaf2502d9d/gomall/app/user/main.go#L80

https://github.com/cloudwego/biz-demo/blob/b0b848231865af4c43f2ed0b8d5967eaf2502d9d/gomall/app/user/infra/mtl/tracing.go#L32

类似这种吧，使用 otlptracehttp 配置下就好了，不需要复制一份代码
