### ISSUE TITLE
failed to upload metrics: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp :4317: connect: connection refused

### ISSUE THREAD

**Issue by hmldd** [kitex-contrib/obs-opentelemetry#48]
Hi，I start a server with obs-opentelemetry and get error: failed to upload metrics: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp :4317: connect: connection refused

I try to check is port in use with: `netstat -tuln | grep 4317` but nothing return，how can i debug it?

**Comment by hmldd** [comment]
The code is: https://github.com/cloudwego/kitex-examples/blob/main/opentelemetry/server/main.go

**Comment by DMwangnima** [comment]
@hmldd Have you followed this ReadMe to start the related components?
![image](https://github.com/user-attachments/assets/fc8aaa17-e017-4db8-8bca-8945acf30cee)

**Comment by hmldd** [comment]
@DMwangnima Thank you for your reply. I skipped the guide and thought it was a data pull port of the server.
