### ISSUE TITLE
最版本版本的依赖不对

### ISSUE THREAD

**Issue by eliohn** [kitex-contrib/obs-opentelemetry#52]
github.com/chenzhuoyu/iasm@v0.9.1: reading github.com/chenzhuoyu/iasm/go.mod at revision v0.9.1: unknown revision v0.9.1
我看开发库已经改了啊，v0.2.8里还是用的这个

**Comment by GuangmingLuo** [comment]
最新版本没有对这个库的依赖，你 go mod tidy 试试

**Comment by GuangmingLuo** [comment]
打了个新 tag v0.2.9，再试试吧
