### ISSUE TITLE
Proposal: need method to specific tracerProvider and Sampler

### ISSUE THREAD

**Issue by rogerogers** [kitex-contrib/obs-opentelemetry#7]
https://github.com/kitex-contrib/obs-opentelemetry/blob/abf075686f15d23ef69c08bf6421315e417528ea/provider/provider.go#L114

this will always be nil

- need sampler option
- need tracerProvider option

otel official provides named global provider, maybe we could reuse this.

**Comment by GuangmingLuo** [comment]
@CoderPoet PTAL

**Comment by CoderPoet** [comment]
@GuangmingLuo @rogerogers Thanks for the feedback, sorry for not paying attention to the issue before, please help review PR #9
